# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
