# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='transient',
            field=models.BooleanField(default=False),
        ),
    ]
