# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 21:34
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rate_transient'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
