# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 22:17
from __future__ import unicode_literals

from django.db import migrations
import tracking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_rate_recurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='primary_income',
            field=tracking.fields.UniqueBooleanField(default=False, help_text='Check this if for the rate that is your primary income.  This is only used in the paycheck explorer report.  Only one is allowed.'),
        ),
    ]
