# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_rate_primary_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='primary_income',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='recurrences',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='transient',
        ),
    ]
